### ISSUE TITLE
http://127.0.0.1:4000/posts/Pomodoro-Project/ site not working

### ISSUE THREAD

**Issue by fulyaertay** [Swag3009/swag3009.github.io#2]
You attached link as http://127.0.0.1:4000/posts/Pomodoro-Project/ but i think it works on your local machine not deployed on internet. Maybe you can deploy it on netlify or Github pages.

**Comment by Swag3009** [comment]
Hey, thanks for raising the issue. I have deployed my site here. [deployed site](https://swag3009.github.io/posts/Pomodoro-Project/). Can you do another favor? Can you please tell me from where did you got that link. Maybe somewhere mistakenly I have attached that link. I'll rectify that.

**Comment by fulyaertay** [comment]
I checked for that link now and i did not see any problem and i have to say that you designed pages very well. Keep coding.☺️
